import "server-only";

import type { Dimension } from "./tag-registry";

/**
 * Regex matchers for SEO tags. Server-only: `TAG_REGISTRY` is imported by
 * client components, and a single unsupported regex literal in that shared
 * chunk is a SyntaxError for the whole page (Safari < 16.4 lookbehind).
 *
 * Node scripts and `tsx --test` do not set the `react-server` export
 * condition, so `server-only` throws there. Import this module only after
 * `ensureReactServerCondition()` (ingest scripts) or via
 * `tsx --conditions react-server`.
 *
 * New registry tags need a key here (an empty array matches nothing).
 * The auto-appender in `src/fill-seo-tags.ts` inserts stubs before
 * TAG_PATTERNS_END.
 */
export const TAG_PATTERNS: Record<string, readonly RegExp[]> = {
  "audience_tag:devushka": [/девушк|женщин|женск|леди|дам[аыу](?![а-яё])|модель\s+в\s+платье|в\s+юбке|макияж.*портрет|портрет.*макияж/i],
  "audience_tag:muzhchina": [/мужчин|мужск|парень|молодой\s+человек|мужик/i],
  "audience_tag:para": [/пар[аыу](?![а-яё])|парн|вдвоем/i],
  "audience_tag:semya": [/семейн(?!ого\s+(альбом|архив))|семья/i],
  "audience_tag:detskie": [/детск|ребен/i],
  "audience_tag:s_mamoy": [/с мамой|мам[аыуе](?![а-яё])|мамочк|мамул|мать(?![а-яё])|матери(?![а-яё])|матерью/i],
  "audience_tag:s_papoy": [/с папой|пап[аыуе](?![а-яё])|папочк|отец|отц[ауе]/i],
  "audience_tag:s_parnem": [/с парнем|парн[яюеи]|бойфренд/i],
  "audience_tag:s_muzhem": [/с мужем|муж[аеу](?![чс])|супруг/i],
  "audience_tag:s_podrugoy": [/с подругой|подруг[аиу]|подружк/i],
  "audience_tag:s_drugom": [/с другом|друг[аеу](?![а-яё])|дружк/i],
  "audience_tag:s_synom": [/с сыном|сын[оу](?![а-яё])|сыноч|сынишк/i],
  "audience_tag:s_dochkoy": [/с дочкой|с дочерью|дочк[аиу]|дочь|дочер/i],
  "audience_tag:s_sestroy": [/с сестрой|сестр[аыуе]|сестрёнк|сестренк/i],
  "audience_tag:s_bratom": [/с братом|брат[аеу](?![а-яё])|братик|братишк/i],
  "audience_tag:s_babushkoy": [/с бабушкой|бабушк[аиу]|бабул/i],
  "audience_tag:malchik": [/мальчик/i],
  "audience_tag:devochka": [/девочка/i],
  "audience_tag:podrostok": [/подросток/i],
  "audience_tag:malysh": [/малыш|младенец/i],
  "audience_tag:pokoleniy": [/поколений|поколения/i],
  "audience_tag:vlyublennykh": [/влюблён|влюблен/i],
  "audience_tag:s_pitomcem": [/с питомц|с животн/i],
  "audience_tag:beremennaya": [/беременн/i],
  "style_tag:cherno_beloe": [/черно-бел|чёрно-бел|монохром/i],
  "style_tag:realistichnoe": [/реалист|фотореализ|гиперреалист/i],
  "style_tag:portret": [/портрет/i],
  "style_tag:3d": [/3д|3d/i],
  "style_tag:gta": [/гта|gta/i],
  "style_tag:studiynoe": [/студийн|студи[яюей](?![а-яё])|studio/i],
  "style_tag:love_is": [/love is|лав ис/i],
  "style_tag:delovoe": [/делов|бизнес/i],
  "style_tag:multyashnoe": [/мультяш|мультик/i],
  "style_tag:kollazh": [/коллаж/i],
  "style_tag:otkrytka": [/открытк/i],
  "style_tag:sovetskoe": [/совет/i],
  "style_tag:retro": [/ретро/i],
  "style_tag:anime": [/аниме/i],
  "style_tag:polaroid": [/полароид|polaroid/i],
  "style_tag:disney": [/дисней|disney/i],
  "style_tag:selfi": [/селфи|selfie|зеркальн\w+\s+фот/i],
  "style_tag:piksar": [/пиксар|pixar/i],
  "style_tag:neonovoe": [/неоновый\s+стиль|неоновое\s+фото|неоновая\s+(подсветка|съёмка|фотосессия)|в\s+неоновом\s+стиле|под\s+неоновыми\s+огнями|неон(?![а-яё])|neon\b/i],
  "style_tag:street_style": [/street.?style|стрит.?стайл/i],
  "style_tag:fashion": [/fashion|фэшн|фешн/i],
  "style_tag:glyanec": [/глянц|журнал(?![а-яё])/i],
  "style_tag:victorias_secret": [/victoria.?s secret|виктория.?сикрет/i],
  "style_tag:barbie": [/barbie|барби/i],
  "occasion_tag:den_rozhdeniya": [/день рождения|на др(?![а-яё])/i],
  "occasion_tag:8_marta": [/8 марта/i],
  "occasion_tag:1_sentyabrya": [/1\s*сентябр|первое\s*сентябр|день\s*знан/i],
  "occasion_tag:14_fevralya": [/14 февраля|день влюбленных|валентин/i],
  "occasion_tag:23_fevralya": [/23 февраля/i],
  "occasion_tag:maslenica": [/маслениц/i],
  "occasion_tag:novyy_god": [/новый год|новогодн/i],
  "occasion_tag:svadba": [/свадьб/i],
  "occasion_tag:rozhdestvo": [/рождеств|christmas/i],
  "occasion_tag:den_uchitelya": [/д(?:ень|ня|ню|нем|нём)\s+учител|(?:^|[^а-яё])учител|(?:^|[^a-z])teacher\b/i],
  "occasion_tag:den_vospitatelya": [/д(?:ень|ня|ню|нем|нём)\s+воспитател|(?:^|[^а-яё])воспитател(?!ьн(?:ый|ая|ое|ые|ого))/i],
  "object_tag:v_forme": [/в форм|военн|солдат/i],
  "object_tag:s_mashinoy": [/с машин|авто|тачк/i],
  "object_tag:s_cvetami": [/с цвет|букет|тюльпан|роз[аыуой]|розов|розам|пион|мимоз|ромашк|лепестк|сирен|цветоч|цвет[оа]к|лаванд|орхиде|гортенз/i],
  "object_tag:so_znamenitostyu": [/со знаменит|с кумир|со звезд/i],
  "object_tag:v_profil": [/в профиль|боком/i],
  "object_tag:s_kotom": [/с кот|котёнк|котенк|кошк|кошеч/i],
  "object_tag:v_kostyume": [/в костюм|в пиджак/i],
  "object_tag:na_chernom_fone": [/на\s+чёрн\w*\s+фон|на\s+черн\w*\s+фон|тёмн\w+\s+фон|чёрный\s+фон|черный\s+фон/i],
  "object_tag:s_tortom": [/с торт/i],
  "object_tag:zima": [/зимн|снег|заснеж|мороз|метел|иней|сугроб|холодн\w+\s+(свет|воздух|утр|вечер)/i],
  "object_tag:v_zerkale": [/в зеркал/i],
  "object_tag:vesna": [/весенн|весна|в\s+цвету|цветущ/i],
  "object_tag:s_sobakoy": [/с собак|пёс|пес(?![а-яё])/i],
  "object_tag:v_lesu": [/в лес|лесн|деревь|ёлк|елок|берёз|хвойн|сосн/i],
  "object_tag:s_koronoy": [/с корон/i],
  "object_tag:na_more": [/на мор|пляж|океан|побереж|прибой|набережн|у\s+моря/i],
  "object_tag:v_polnyy_rost": [/в полный рост|во\s+весь\s+рост|в\s+рост(?![а-яё])/i],
  "object_tag:v_gorah": [/в\s+гор(?!од)|горн\w+\s+(пейзаж|вершин|хребет|склон)/i],
  "object_tag:na_ulice": [/на улиц|уличн|переулк/i],
  "object_tag:v_mashine": [/в машин|за рулём|за рулем|в салоне авто/i],
  "object_tag:na_yahte": [/на яхте|яхт[аыуе](?![а-яё])/i],
  "object_tag:v_restorane": [/в ресторан|в кафе|бистро/i],
  "object_tag:na_kryshe": [/на крыш/i],
  "object_tag:v_pustyne": [/в пустын|барханы|барханов/i],
  "object_tag:pod_vodoy": [/под водой|подводн/i],
  "object_tag:v_gorode": [/небоскрёб|небоскреб|мегапол|городск|на\s+фоне\s+город|ночн\w+\s+город/i],
  "object_tag:s_shuboj": [/в шубе|шуба|шубой|меховой|меховая|меховую/i],
  "object_tag:so_svechami": [/со свеч|при свечах|свечой|свечей|свечи|свечам|свечу|свеча/i],
  "object_tag:v_platye": [/в платье|платья|платьем/i],
  "object_tag:s_bokalom": [/бокал/i],
  "object_tag:s_kofe": [/кофе|чашечк/i],
  "object_tag:na_avatarku": [/на аватарк|на аву|аватар/i],
  "style_tag:kinematograficheskoe": [/кинематограф/i],
  "style_tag:y2k": [/y2k/i],
  "style_tag:lifestyle": [/лайфстайл|lifestyle/i],
  "style_tag:vintazhnoe": [/винтаж|vintage/i],
  "object_tag:s_elkoj": [/с ёлк|с елк|ёлочк|елочк/i],
  "object_tag:s_sharami": [/с шар|воздушн\w+\s+шар|шарик/i],
  "object_tag:na_belom_fone": [/на\s+бел\w*\s+фон|белый\s+фон/i],
  "object_tag:v_interere": [/в интерьер|интерьерн/i],
  "object_tag:s_podarkami": [/с подарк|подарочн/i],
  "object_tag:s_ochkami": [/с очками|в очках|очки/i],
  "style_tag:fotorealizm": [],
  "style_tag:minimalizm": [],
  "style_tag:vysokaya_moda": [],
  "object_tag:s_pitomcem": [],
  "style_tag:editorial": [],
  "object_tag:noch": [],
  "object_tag:osen": [/осенн|осень|листопад|жёлтые\s+лист|желтые\s+лист/i],
  "object_tag:leto": [/летн|лето(?![а-яё])/i],
  "object_tag:v_pole": [/в\s+пол[ею]|полевы|среди\s+колос/i],
  "object_tag:s_loshadyu": [/с лошадью|лошад|конь|коня|конём/i],
  "style_tag:romanticheskiy": [/романтич/i],
  "style_tag:bokho_stil": [/бохо|boho/i],
  "style_tag:etno_stil": [/этно|ethno/i],
  "style_tag:ultrarealistichnoe": [/ultra.?realist|ультрареалист/i],
  "object_tag:s_shuboy": [/в\s+шуб|с\s+шуб|шуба|шубк/i],
  "object_tag:v_basseyne": [/в\s+бассейн|бассейн/i],
  "object_tag:vintazhnyy_avtomobil": [/винтажн\S*\s+авто|ретро.?авто|старинн\S*\s+авто|vintage\s+car/i],
  "object_tag:s_medvedem": [/с\s+медвед|медведь|медведем/i],
  "style_tag:glam": [/глэм|глам|glam/i],
  "object_tag:v_sportale": [/в\s+спортзал|в\s+тренажёрн|в\s+тренажерн|спортзал|gym/i],
  "object_tag:na_krovati": [/на\s+кроват|в\s+кроват|в\s+постел|на\s+постел/i],
  "occasion_tag:halloween": [/хэллоуин|хеллоуин|halloween|hellouin/i],
  "doc_task_tag:na_pasport": [/на паспорт|паспортн/i],
  "doc_task_tag:na_dokumenty": [/на документ/i],
  "doc_task_tag:na_rezume": [/для резюме|на резюме|резюме/i],
  "doc_task_tag:na_zagranpasport": [/загранпаспорт|загран/i],
  "object_tag:v_studii": [/в\s+студи|студийн/i],
  "style_tag:produktovaya_fotografiya": [/продуктов\S*\s+фото|product\s+photo/i],
  "style_tag:art_deco": [/арт.?деко|art.?deco/i],
  "object_tag:na_naberezhnoj": [/на\s+набережн|набережн/i],
  "style_tag:giperrealistichnoe": [/гиперреалист|hyperrealist/i],
  "object_tag:na_okne": [/у\s+окн|на\s+окн|возле\s+окн|у\s+подоконник/i],
  "object_tag:na_balkone": [/на\s+балкон|балкон/i],
  "object_tag:v_metroe": [/в\s+метро|метро/i],
  "object_tag:v_lifte": [/в\s+лифт|лифт/i],
  "object_tag:v_parke": [/в\s+парк|парков/i],
  "style_tag:impressionizm": [/импрессионизм|impressionism/i],
  "object_tag:v_spalne": [/в\s+спальн|спальня/i],
  "object_tag:kuhnya": [/на\s+кухн|кухня|кухонн/i],
  "object_tag:v_sadu": [/в\s+саду|садов|в\s+сад(?![а-яё])/i],
  "object_tag:v_vannoy": [/в\s+ванн|ванная|ванной/i],
  "object_tag:sneg": [/снег|снежн|снежинк|снегопад/i],
  "object_tag:dozhd": [/дожд|ливен|ливн/i],
  "object_tag:tuman": [/туман|fog/i],
  "object_tag:zakat": [/закат|sunset|рассвет/i],
  "object_tag:zolotoy_chas": [/золот\S*\s+час|golden\s+hour/i],
  "object_tag:mototsikl": [/мотоцикл|байк(?![а-яё])|motorcycle/i],
  "object_tag:velosiped": [/велосипед|bicycle/i],
  "object_tag:s_tulpanami": [/тюльпан/i],
  "object_tag:s_shampanskim": [/шампанск/i],
  "object_tag:s_detskim_foto": [/детск(?:им|ой)\s+фото|детской\s+фотографи|маленькой\s+собой|с\s+собой\s+маленьк/i],
  "object_tag:so_lvom": [/со\s+львом|с\s+львом|львом(?![а-яё])/i],
  "object_tag:s_zontom": [/с\s+зонт|зонтик|зонтом|umbrella/i],
  "object_tag:s_knigoy": [/с\s+книг|книга|книжк/i],
  "object_tag:s_gitaroy": [/гитар|guitar/i],
  "object_tag:s_tykvoy": [/тыкв|pumpkin/i],
  "object_tag:s_naushnikami": [/наушник|headphone/i],
  "object_tag:s_mandarinami": [/мандарин/i],
  "object_tag:s_girlyandami": [/гирлянд/i],
  "object_tag:iphone": [/iphone|айфон/i],
  "style_tag:fine_art": [/fine\s*art|файн\s*арт/i],
  "object_tag:s_samovarom": [/самовар/i],
  "object_tag:na_krasnom_fone": [/на\s+красн\w*\s+фон|красный\s+фон/i],
  "object_tag:na_rozovom_fone": [/на\s+розов\w*\s+фон|розовый\s+фон/i],
  "object_tag:s_maskoy": [/с\s+маск|маска|маске|маской/i],
  "object_tag:s_konfetami": [/конфет|сладост/i],
  "object_tag:s_igrushkoy": [/с\s+игрушк|игрушечн|плюшев/i],
  "object_tag:na_lestnice": [/на\s+лестниц|лестница|ступен/i],
  "object_tag:s_zhurnalom": [/с\s+журнал|журнал(?!ьн)/i],
  "object_tag:s_pionami": [/пион|пионы|с\s+пионами/i],
  "object_tag:s_valentinkami": [/валентинк|с\s+валентинками/i],
  "object_tag:s_shokoladkoy": [/шоколадк|с\s+шоколад/i],
  "object_tag:s_otkrytkami": [/с\s+открытками|с\s+открыткой/i],
  "object_tag:s_serdechkami": [/сердечк|с\s+сердцем|с\s+сердечками/i],
  "object_tag:s_lentami": [/с\s+лентами|ленточк|ленты/i],
  "object_tag:na_stole": [/на\s+столе|на\s+столик|на\s+поверхности\s+стола/i],
  "object_tag:s_cheburashkoy": [/чебурашк|с\s+чебурашкой/i],
  // TAG_PATTERNS_END
};

export function patternsForTag(dimension: Dimension, slug: string): readonly RegExp[] {
  return TAG_PATTERNS[`${dimension}:${slug}`] ?? [];
}
