-- Robokassa one-time token purchases and provider-neutral admin read model.

CREATE TABLE IF NOT EXISTS public.landing_robokassa_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  auth_user_id uuid NOT NULL,
  landing_user_id uuid NOT NULL REFERENCES public.landing_users(id),
  plan_id text NOT NULL,
  credits integer NOT NULL CHECK (credits > 0),
  amount_rub numeric(10, 2) NOT NULL CHECK (amount_rub > 0),
  idempotency_key uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  status text NOT NULL DEFAULT 'created'
    CHECK (status IN ('created', 'pending', 'succeeded', 'canceled')),
  provider_status text,
  payment_method text,
  test boolean NOT NULL DEFAULT false,
  ym_client_id text,
  yclid text,
  yandex_conversion_sent_at timestamptz,
  yandex_conversion_claimed_at timestamptz,
  yandex_conversion_attempts integer NOT NULL DEFAULT 0,
  yandex_conversion_error text,
  credited_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_landing_robokassa_auth_created
  ON public.landing_robokassa_payments(auth_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_landing_robokassa_user_created
  ON public.landing_robokassa_payments(landing_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_landing_robokassa_pending
  ON public.landing_robokassa_payments(status, created_at)
  WHERE status IN ('created', 'pending');

CREATE INDEX IF NOT EXISTS idx_landing_robokassa_admin_status_created
  ON public.landing_robokassa_payments(status, created_at DESC, id DESC);

ALTER TABLE public.landing_robokassa_payments ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.landing_yookassa_payments
  ADD COLUMN IF NOT EXISTS yandex_conversion_claimed_at timestamptz;

CREATE OR REPLACE FUNCTION public.landing_fulfill_robokassa_payment(
  p_payment_id uuid,
  p_invoice_id bigint,
  p_payment_method text,
  p_test boolean
)
RETURNS TABLE(credited boolean, credits_after integer, payment_status text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_payment public.landing_robokassa_payments%ROWTYPE;
  v_credits_after integer;
BEGIN
  SELECT *
    INTO v_payment
    FROM public.landing_robokassa_payments
   WHERE id = p_payment_id
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'payment_not_found' USING ERRCODE = 'P0001';
  END IF;

  IF v_payment.invoice_id IS DISTINCT FROM p_invoice_id THEN
    RAISE EXCEPTION 'provider_payment_mismatch' USING ERRCODE = 'P0001';
  END IF;

  IF v_payment.credited_at IS NOT NULL THEN
    SELECT credits
      INTO v_credits_after
      FROM public.landing_users
     WHERE id = v_payment.landing_user_id;

    RETURN QUERY
      SELECT false, COALESCE(v_credits_after, 0), v_payment.status;
    RETURN;
  END IF;

  UPDATE public.landing_users
     SET credits = credits + v_payment.credits,
         updated_at = now()
   WHERE id = v_payment.landing_user_id
   RETURNING credits INTO v_credits_after;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'landing_user_not_found' USING ERRCODE = 'P0001';
  END IF;

  UPDATE public.landing_robokassa_payments
     SET status = 'succeeded',
         provider_status = 'succeeded',
         payment_method = NULLIF(p_payment_method, ''),
         test = p_test,
         credited_at = now(),
         updated_at = now()
   WHERE id = p_payment_id;

  RETURN QUERY SELECT true, v_credits_after, 'succeeded'::text;
END;
$$;

REVOKE ALL ON FUNCTION public.landing_fulfill_robokassa_payment(uuid, bigint, text, boolean)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.landing_fulfill_robokassa_payment(uuid, bigint, text, boolean)
  TO service_role;

CREATE OR REPLACE FUNCTION public.admin_landing_payments(
  p_status text DEFAULT 'all',
  p_test boolean DEFAULT NULL,
  p_cursor_created_at timestamptz DEFAULT NULL,
  p_cursor_id uuid DEFAULT NULL,
  p_limit integer DEFAULT 30
) RETURNS TABLE (
  id uuid,
  provider text,
  provider_payment_id text,
  created_at timestamptz,
  updated_at timestamptz,
  auth_user_id uuid,
  landing_user_id uuid,
  payer_email text,
  payer_display_name text,
  payer_provider text,
  plan_id text,
  credits integer,
  amount_rub numeric,
  status text,
  provider_status text,
  test boolean,
  credited_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH payments AS (
    SELECT
      yp.id,
      'yookassa'::text AS provider,
      yp.yookassa_payment_id AS provider_payment_id,
      yp.created_at,
      yp.updated_at,
      yp.auth_user_id,
      yp.landing_user_id,
      yp.plan_id,
      yp.credits,
      yp.amount_rub,
      yp.status,
      yp.provider_status,
      yp.test,
      yp.credited_at
    FROM public.landing_yookassa_payments yp
    UNION ALL
    SELECT
      rp.id,
      'robokassa'::text AS provider,
      rp.invoice_id::text AS provider_payment_id,
      rp.created_at,
      rp.updated_at,
      rp.auth_user_id,
      rp.landing_user_id,
      rp.plan_id,
      rp.credits,
      rp.amount_rub,
      rp.status,
      rp.provider_status,
      rp.test,
      rp.credited_at
    FROM public.landing_robokassa_payments rp
  )
  SELECT
    p.id,
    p.provider,
    p.provider_payment_id,
    p.created_at,
    p.updated_at,
    p.auth_user_id,
    p.landing_user_id,
    COALESCE(NULLIF(au.email, ''), NULLIF(iu.email, '')) AS payer_email,
    COALESCE(
      NULLIF(lu.display_name, ''),
      NULLIF(au.raw_user_meta_data ->> 'full_name', ''),
      NULLIF(au.raw_user_meta_data ->> 'name', ''),
      NULLIF(iu.display_name, '')
    ) AS payer_display_name,
    COALESCE(
      NULLIF(lu.provider, ''),
      NULLIF(au.raw_app_meta_data ->> 'provider', '')
    ) AS payer_provider,
    p.plan_id,
    p.credits,
    p.amount_rub,
    p.status,
    p.provider_status,
    p.test,
    p.credited_at
  FROM payments p
  LEFT JOIN auth.users au ON au.id = p.auth_user_id
  LEFT JOIN public.landing_users lu ON lu.id = p.landing_user_id
  LEFT JOIN public.imageprompt_users iu ON iu.id = p.landing_user_id
  WHERE (
      lower(COALESCE(p_status, 'all')) = 'all'
      OR p.status = lower(p_status)
    )
    AND (p_test IS NULL OR p.test IS NOT DISTINCT FROM p_test)
    AND (
      p_cursor_created_at IS NULL
      OR p_cursor_id IS NULL
      OR p.created_at < p_cursor_created_at
      OR (p.created_at = p_cursor_created_at AND p.id < p_cursor_id)
    )
  ORDER BY p.created_at DESC, p.id DESC
  LIMIT greatest(1, least(COALESCE(p_limit, 30), 100)) + 1;
$$;

REVOKE ALL ON FUNCTION public.admin_landing_payments(text, boolean, timestamptz, uuid, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_landing_payments(text, boolean, timestamptz, uuid, integer)
  TO service_role;

COMMENT ON TABLE public.landing_robokassa_payments IS
  'Server-only ledger for one-time PromptShot token purchases through Robokassa.';
